package com.bsb.hike.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Metric implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Object user;
	private Object ts;
	private java.lang.String metric_name;
	private int value;

	public Metric() {
	}

	public Object getUser() {
		return this.user;
	}

	public void setUser(Object user) {
		this.user = user;
	}

	public Object getTs() {
		return this.ts;
	}

	public void setTs(Object ts) {
		this.ts = ts;
	}

	public java.lang.String getMetric_name() {
		return this.metric_name;
	}

	public void setMetric_name(java.lang.String metric_name) {
		this.metric_name = metric_name;
	}

	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public Metric(Object user, Object ts,
			java.lang.String metric_name, int value) {
		this.user = user;
		this.ts = ts;
		this.metric_name = metric_name;
		this.value = value;
	}

	@Override
	public String toString() {
		return "Metric [user=" + user + ", ts=" + ts + ", metric_name=" + metric_name + ", value=" + value + "]";
	}

}